### PR TITLE
Explicit imports

### LINKED ISSUE #99: Bad test now errors
Don't know what this is trying to test exactly:

https://github.com/JuliaRegistries/RegistryTools.jl/blob/77e2a02e62185ce865653bdae95203a3a40510f0/test/regedit.jl#L333-L336

Right now it gets

```
compat_file: Test Failed at /home/pkgeval/.julia/packages/RegistryTools/2CM18/test/regedit.jl:333
  Expression: read(compat_file, String) == "[1]\njulia = \"1.3.0-1\"\n"
   Evaluated: "[1]\njulia = \"1.3.0 - 1\"\n" == "[1]\njulia = \"1.3.0-1\"\n"
``

### PR DESCRIPTION
**Pull request by GunnarFarneback**
* Stop doing implicit imports and be explicit about all imports. Thanks to @ericphanson for ExplicitImports.jl.
* Make regression tests of compat files ignore whitespace around hyphens. Fixes #99.
* Remove dependency on AutoHashEquals. This was only used for a roundtrip test of the `RegistryData` struct and had no reasonable utility externally. Closes #95.
* (Added) Check in the tests that imports remain explicit.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Could we also run ExplicitImports.jl as part of the test suite here, to make sure this doesn't regress?

**Comment by GunnarFarneback** [comment]
Maybe? ExplicitImports gives a note about `Pkg.Types.semver_spec` actually being owned by `Pkg.Versions.semver_spec`, but that is only true for sufficiently new Julia versions.

**Comment by DilumAluthge** [comment]
Would ExplicitImports be satisfied by:

```julia
@static if VERSION >= v"1.9-" # or whatever the correct version is
    const semver_spec = Pkg.Versions.semver_spec
else
    const semver_spec = Pkg.Types.semver_spec
end

**Comment by GunnarFarneback** [comment]
It's not really worth being that pedantic in the code. But when I checked the ExplicitImports README, the regression checking functions are quite specific about what things they look for.

**Comment by DilumAluthge** [comment]
@ericphanson What are your thoughts here? Could we run ExplicitImports in the test suite, but just tell ExplicitImports to skip `semver_spec`?

I would also be fine with doing the `@static if...`, even though it is a little annoying.

**Comment by GunnarFarneback** [comment]
A bigger problem is that ExplicitImports doesn't work with as old versions as RegistryTools.

**Comment by DilumAluthge** [comment]
We could omit ExplicitImports from the list of test-deps, and then in the test suite, if the Julia version is new enough, we could do `Pkg.add(name = "ExplicitImports", uuid = "...", preserve=Pkg.PRESERVE_ALL)`.

**Comment by GunnarFarneback** [comment]
It ain't pretty, but yes, it works.

**Comment by ericphanson** [comment]
The regression testing functions have an `ignore` kwarg to skip stuff like this btw! Also `skip` for whole modules.

**Review by ericphanson — APPROVED** [review]

File: test/runtests.jl [hunk 1]
```diff
@@ -1,9 +1,22 @@
...
 @testset "RegistryTools" begin
 
 include("regedit.jl")
 include("compress.jl")
 
+# ExplicitImports does not support as old Julia versions as RegistryTools does.
+# Change this to a regular test dependency when it becomes possible, i.e.
+# when pre-1.7 support is dropped.
+if VERSION >= v"1.7"
+Pkg.add(name = "ExplicitImports", uuid = "7d51a73a-1435-4ff3-83d9-f097790105c7", preserve=Pkg.PRESERVE_ALL)
```
Comment (ericphanson) [inline test/runtests.jl:14]: it would be nice to drop this... also to get ExplicitImports into Aqua.. at some point I will see about expanding compat
