### PR TITLE
Fix Compress.compress with mixed String/UUID input data, fixes #46.

### LINKED ISSUE #46: Doesn't compress dependencies with Julia v1.6
See

* https://github.com/JuliaRegistries/General/commit/581f65873a51ebf31e7ac866e52723c403a9e870#diff-a8040c6047a79184f490209a15a9d343
* https://github.com/JuliaRegistries/General/commit/7e678ed6632b7856f82d8c72a7aa8f6d7037ed11#diff-ff516c7a7195ef333bcd3158dcf44801
* https://github.com/JuliaRegistries/General/commit/2c205785445506a1b68e378517ac0aeeb1a546dc#diff-5ced124a3c260b01c7910b63897e735a

### PR DESCRIPTION
**Pull request by fredrikekre**
Fixes #46

### CODE REVIEW

File: src/Compress.jl [hunk 1]
```diff
@@ -73,14 +73,11 @@ end
 
 function compress(path::String, uncompressed::Dict,
                   versions::Vector{VersionNumber} = load_versions(path))
-    inverted = Dict()
+    inverted = Dict{Pair{String,String},Vector{VersionNumber}}()
     for (ver, data) in uncompressed, (key, val) in data
-        if !STDLIB_TOML
-            val isa TOML.TYPE || (val = string(val))
-        end
-        push!(get!(inverted, key => val, VersionNumber[]), ver)
```
Comment (fredrikekre) [inline src/Compress.jl:81]: Turns out that we need to stringify already here since the dict keys will be different when some input UUIDs are `String` and some `Base.UUID`...
